// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"goframe-v2.5/app/user-manager/internal/dao/internal"
)

// internalCaCertDeviceIdDao is internal type for wrapping internal DAO implements.
type internalCaCertDeviceIdDao = *internal.CaCertDeviceIdDao

// caCertDeviceIdDao is the data access object for table ca_cert_deviceId.
// You can define custom methods on it to extend its functionality as you wish.
type caCertDeviceIdDao struct {
	internalCaCertDeviceIdDao
}

var (
	// CaCertDeviceId is globally public accessible object for table ca_cert_deviceId operations.
	CaCertDeviceId = caCertDeviceIdDao{
		internal.NewCaCertDeviceIdDao(),
	}
)

// Fill with you ideas below.
