// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"goframe-v2.5/app/user-manager/internal/dao/internal"
)

// internalCaCertInfoDao is internal type for wrapping internal DAO implements.
type internalCaCertInfoDao = *internal.CaCertInfoDao

// caCertInfoDao is the data access object for table ca_cert_info.
// You can define custom methods on it to extend its functionality as you wish.
type caCertInfoDao struct {
	internalCaCertInfoDao
}

var (
	// CaCertInfo is globally public accessible object for table ca_cert_info operations.
	CaCertInfo = caCertInfoDao{
		internal.NewCaCertInfoDao(),
	}
)

// Fill with you ideas below.
