// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"goframe-v2.5/app/user-manager/internal/dao/internal"
)

// internalCaIssuerInfoDao is internal type for wrapping internal DAO implements.
type internalCaIssuerInfoDao = *internal.CaIssuerInfoDao

// caIssuerInfoDao is the data access object for table ca_issuer_info.
// You can define custom methods on it to extend its functionality as you wish.
type caIssuerInfoDao struct {
	internalCaIssuerInfoDao
}

var (
	// CaIssuerInfo is globally public accessible object for table ca_issuer_info operations.
	CaIssuerInfo = caIssuerInfoDao{
		internal.NewCaIssuerInfoDao(),
	}
)

// Fill with you ideas below.
